services:
  s1app:
    image: prawee/strapi:latest
    container_name: 68-s1-app
    ports:
      - ${APP_PORT}:1337
    environment:
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_HOST: s1db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${POSTGRES_USER}

    depends_on:
      - s1db
    networks:
      - s1_network