# ส่วนที่ 1: รับ HTTP แล้วโยนไป HTTPS
server {
    listen 80;
    server_name cybersec.group;
    return 301 https://$host$request_uri;
}

# ส่วนที่ 2: ส่วนของ SSL
server {
    listen 443 ssl; # <--- ต้องมีคำว่า ssl ตรงนี้!
    server_name cybersec.group;

    ssl_certificate     /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

    location / {
        # ตรงนี้สำคัญ: Nginx คุยกับ Strapi (s1app) ต้องใช้ http ปกติ
        proxy_pass http://s1app:1337; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # ตัวนี้จะบอก Strapi ว่าคนเข้าใช้ https
    }
}